apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/social-network-app-mynet: "true"
        io.kompose.service: broker
    spec:
      containers:
        - env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_LISTENERS
              value: CLIENT://:9092,INTERNAL://:9093,
            - name: KAFKA_ADVERTISED_LISTENERS
              value: CLIENT://broker:9092,INTERNAL://localhost:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
#        - env:
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#            - name: KAFKA_BROKER_ID
#              value: "1"
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#              value: "1"
#            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
#              value: "1"
#            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
#              value: "1"
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zookeeper:2181
          image: confluentinc/cp-kafka:7.0.1
          name: broker
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
